[project]
name = "ios_camera"
version = "0.1.0"
description = "Add your description here"
  
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = [
    "setuptools>=61",
    "sh"
]
build-backend = "setuptools.build_meta"